#!/bin/bash
if [ $EUID != 0 ]; then
	echo "$0: Es necesario ejecutar este programa con permisos de administrador"
	exit -1
fi

function addedFilesChecker(){
for ((i=1; i<5; i++)); do
	while IFS=" " read -r name permissions md5sum; do
		flag=0
		while IFS=" " read -r oriName oriPermissions oriMd5sum; do
			[[ $name == $oriName ]] && flag=1 && break
		done<"/etc/binChecker/$i"	
		[[ $flag -eq 0 ]] && echo "  -El archivo $name ha sido añadido">>/var/log/binChecker
	done<"$1/$i"
done
}

function filesChecker(){
for ((i=1; i<5; i++)); do
	while IFS=" " read -r oriName oriPermissions oriMd5sum; do
		flag=0
		while IFS=" " read -r name permissions md5sum; do
			[[ $name == $oriName ]] && flag=1 && break
		done<"$1/$i"	
			[[ $flag -eq 0 ]] && echo "  -El archivo $name ha sido eliminado">>/var/log/binChecker && continue
			[[ $permissions == $oriPermissions ]] || printf "  -Los permisos del archivo $name han sido alterados: \n    Permisos actuales: $permissions \n    Permisos originales: $oriPermissions\n">>/var/log/binChecker
			[[ $md5sum == $oriMd5sum ]] || printf "  -El contenido del archivo $name ha sido alterado: \n    Suma de control actual: $md5sum \n    Suma de control original: $oriMd5sum \n">>/var/log/binChecker
	done<"/etc/binChecker/$i"
done

addedFilesChecker $1
}


echo "[BinChecker] Comprobación con fecha : $(date +"%d-%m-%Y")" >>/var/log/binChecker

tmpdir="/tmp/binChecker"
mkdir -p "$tmpdir/"
/opt/binChecker/snapshot $tmpdir

filesChecker $tmpdir
rm -rf $tmpdir

echo "[BinChecker] Comprobación finalizada" >>/var/log/binChecker

exit 0
